tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - vscjava.vscode-java-test
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
